title: "Noah Ringrose"
description: "Personal website of Noah Ringrose, physics PhD student at NYU interested in QFT, topological phases of matter, and category theory."
theme: minima
author: Noah Ringrose
markdown: kramdown

# Links
email: noah.ringrose@gmail.com
github_username: noahringrose

# Navigation links
header_pages:
  - blog.md
  - index.md
