title: Noah Ringrose's personal website
description: Welcome to my personal website.
theme: minima
author: Noah Ringrose
markdown: kramdown

# Links
email: noah.ringrose@gmail.com
github_username: noahringrose

# Navigation links
header_pages:
  - index.md
  - blog.md
